# Generated by Django 4.2 on 2023-04-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artists.artist'),
        ),
        migrations.DeleteModel(
            name='AlbumArtist',
        ),
    ]
